import Foundation

/// Abstract data type of an information element (RFC 7012 §3.1).
public enum IEDataType: String, Sendable, Codable {
    case octetArray, unsigned8, unsigned16, unsigned32, unsigned64, signed8, signed16, signed32, signed64
    case float32, float64, boolean, macAddress, string, dateTimeSeconds, dateTimeMilliseconds
    case dateTimeMicroseconds, dateTimeNanoseconds, ipv4Address, ipv6Address, basicList, subTemplateList, subTemplateMultiList
}

public struct InformationElementInfo: Sendable, Hashable {
    public let id: UInt16
    public let name: String
    public let type: IEDataType
    public init(_ id: UInt16, _ name: String, _ type: IEDataType) { self.id = id; self.name = name; self.type = type }
}

/// IANA IPFIX information element registry (subset covering flow export, options, PSAMP sampling and
/// NAT). Unknown elements decode as octetArray and are preserved in `FlowRecord.extraElements`.
public enum IANAInformationElements {
    public static let reversePEN: UInt32 = 29305

    nonisolated(unsafe) public static let byID: [UInt16: InformationElementInfo] = {
        var m: [UInt16: InformationElementInfo] = [:]
        for e in all { m[e.id] = e }
        return m
    }()

    public static func info(_ id: UInt16) -> InformationElementInfo? { byID[id] }

    public static let all: [InformationElementInfo] = [
        .init(1, "octetDeltaCount", .unsigned64), .init(2, "packetDeltaCount", .unsigned64), .init(3, "deltaFlowCount", .unsigned64),
        .init(4, "protocolIdentifier", .unsigned8), .init(5, "ipClassOfService", .unsigned8), .init(6, "tcpControlBits", .unsigned16),
        .init(7, "sourceTransportPort", .unsigned16), .init(8, "sourceIPv4Address", .ipv4Address), .init(9, "sourceIPv4PrefixLength", .unsigned8),
        .init(10, "ingressInterface", .unsigned32), .init(11, "destinationTransportPort", .unsigned16), .init(12, "destinationIPv4Address", .ipv4Address),
        .init(13, "destinationIPv4PrefixLength", .unsigned8), .init(14, "egressInterface", .unsigned32), .init(15, "ipNextHopIPv4Address", .ipv4Address),
        .init(16, "bgpSourceAsNumber", .unsigned32), .init(17, "bgpDestinationAsNumber", .unsigned32), .init(18, "bgpNextHopIPv4Address", .ipv4Address),
        .init(19, "postMCastPacketDeltaCount", .unsigned64), .init(20, "postMCastOctetDeltaCount", .unsigned64),
        .init(21, "flowEndSysUpTime", .unsigned32), .init(22, "flowStartSysUpTime", .unsigned32), .init(23, "postOctetDeltaCount", .unsigned64),
        .init(24, "postPacketDeltaCount", .unsigned64), .init(25, "minimumIpTotalLength", .unsigned64), .init(26, "maximumIpTotalLength", .unsigned64),
        .init(27, "sourceIPv6Address", .ipv6Address), .init(28, "destinationIPv6Address", .ipv6Address), .init(29, "sourceIPv6PrefixLength", .unsigned8),
        .init(30, "destinationIPv6PrefixLength", .unsigned8), .init(31, "flowLabelIPv6", .unsigned32), .init(32, "icmpTypeCodeIPv4", .unsigned16),
        .init(33, "igmpType", .unsigned8), .init(34, "samplingInterval", .unsigned32), .init(35, "samplingAlgorithm", .unsigned8),
        .init(36, "flowActiveTimeout", .unsigned16), .init(37, "flowIdleTimeout", .unsigned16), .init(38, "engineType", .unsigned8), .init(39, "engineId", .unsigned8),
        .init(40, "exportedOctetTotalCount", .unsigned64), .init(41, "exportedMessageTotalCount", .unsigned64), .init(42, "exportedFlowRecordTotalCount", .unsigned64),
        .init(43, "ipv4RouterSc", .ipv4Address), .init(44, "sourceIPv4Prefix", .ipv4Address), .init(45, "destinationIPv4Prefix", .ipv4Address),
        .init(46, "mplsTopLabelType", .unsigned8), .init(47, "mplsTopLabelIPv4Address", .ipv4Address), .init(48, "samplerId", .unsigned8),
        .init(49, "samplerMode", .unsigned8), .init(50, "samplerRandomInterval", .unsigned32), .init(51, "classId", .unsigned8),
        .init(52, "minimumTTL", .unsigned8), .init(53, "maximumTTL", .unsigned8), .init(54, "fragmentIdentification", .unsigned32),
        .init(55, "postIpClassOfService", .unsigned8), .init(56, "sourceMacAddress", .macAddress), .init(57, "postDestinationMacAddress", .macAddress),
        .init(58, "vlanId", .unsigned16), .init(59, "postVlanId", .unsigned16), .init(60, "ipVersion", .unsigned8), .init(61, "flowDirection", .unsigned8),
        .init(62, "ipNextHopIPv6Address", .ipv6Address), .init(63, "bgpNextHopIPv6Address", .ipv6Address), .init(64, "ipv6ExtensionHeaders", .unsigned32),
        .init(70, "mplsTopLabelStackSection", .octetArray), .init(80, "destinationMacAddress", .macAddress), .init(81, "postSourceMacAddress", .macAddress),
        .init(82, "interfaceName", .string), .init(83, "interfaceDescription", .string), .init(85, "octetTotalCount", .unsigned64), .init(86, "packetTotalCount", .unsigned64),
        .init(88, "fragmentOffset", .unsigned16), .init(89, "forwardingStatus", .unsigned8), .init(90, "mplsVpnRouteDistinguisher", .octetArray),
        .init(91, "mplsTopLabelPrefixLength", .unsigned8), .init(94, "applicationDescription", .string), .init(95, "applicationId", .octetArray),
        .init(96, "applicationName", .string), .init(98, "postIpDiffServCodePoint", .unsigned8), .init(99, "multicastReplicationFactor", .unsigned32),
        .init(100, "className", .string), .init(101, "classificationEngineId", .unsigned8), .init(128, "bgpNextAdjacentAsNumber", .unsigned32),
        .init(129, "bgpPrevAdjacentAsNumber", .unsigned32), .init(130, "exporterIPv4Address", .ipv4Address), .init(131, "exporterIPv6Address", .ipv6Address),
        .init(132, "droppedOctetDeltaCount", .unsigned64), .init(133, "droppedPacketDeltaCount", .unsigned64), .init(134, "droppedOctetTotalCount", .unsigned64),
        .init(135, "droppedPacketTotalCount", .unsigned64), .init(136, "flowEndReason", .unsigned8), .init(137, "commonPropertiesId", .unsigned64),
        .init(138, "observationPointId", .unsigned64), .init(139, "icmpTypeCodeIPv6", .unsigned16), .init(140, "mplsTopLabelIPv6Address", .ipv6Address),
        .init(141, "lineCardId", .unsigned32), .init(142, "portId", .unsigned32), .init(143, "meteringProcessId", .unsigned32), .init(144, "exportingProcessId", .unsigned32),
        .init(145, "templateId", .unsigned16), .init(146, "wlanChannelId", .unsigned8), .init(147, "wlanSSID", .string), .init(148, "flowId", .unsigned64),
        .init(149, "observationDomainId", .unsigned32), .init(150, "flowStartSeconds", .dateTimeSeconds), .init(151, "flowEndSeconds", .dateTimeSeconds),
        .init(152, "flowStartMilliseconds", .dateTimeMilliseconds), .init(153, "flowEndMilliseconds", .dateTimeMilliseconds),
        .init(154, "flowStartMicroseconds", .dateTimeMicroseconds), .init(155, "flowEndMicroseconds", .dateTimeMicroseconds),
        .init(156, "flowStartNanoseconds", .dateTimeNanoseconds), .init(157, "flowEndNanoseconds", .dateTimeNanoseconds),
        .init(158, "flowStartDeltaMicroseconds", .unsigned32), .init(159, "flowEndDeltaMicroseconds", .unsigned32),
        .init(160, "systemInitTimeMilliseconds", .dateTimeMilliseconds), .init(161, "flowDurationMilliseconds", .unsigned32), .init(162, "flowDurationMicroseconds", .unsigned32),
        .init(163, "observedFlowTotalCount", .unsigned64), .init(164, "ignoredPacketTotalCount", .unsigned64), .init(165, "ignoredOctetTotalCount", .unsigned64),
        .init(166, "notSentFlowTotalCount", .unsigned64), .init(167, "notSentPacketTotalCount", .unsigned64), .init(168, "notSentOctetTotalCount", .unsigned64),
        .init(169, "destinationIPv6Prefix", .ipv6Address), .init(170, "sourceIPv6Prefix", .ipv6Address), .init(171, "postOctetTotalCount", .unsigned64),
        .init(172, "postPacketTotalCount", .unsigned64), .init(173, "flowKeyIndicator", .unsigned64), .init(174, "postMCastPacketTotalCount", .unsigned64),
        .init(175, "postMCastOctetTotalCount", .unsigned64), .init(176, "icmpTypeIPv4", .unsigned8), .init(177, "icmpCodeIPv4", .unsigned8),
        .init(178, "icmpTypeIPv6", .unsigned8), .init(179, "icmpCodeIPv6", .unsigned8), .init(180, "udpSourcePort", .unsigned16), .init(181, "udpDestinationPort", .unsigned16),
        .init(182, "tcpSourcePort", .unsigned16), .init(183, "tcpDestinationPort", .unsigned16), .init(184, "tcpSequenceNumber", .unsigned32),
        .init(185, "tcpAcknowledgementNumber", .unsigned32), .init(186, "tcpWindowSize", .unsigned16), .init(187, "tcpUrgentPointer", .unsigned16),
        .init(188, "tcpHeaderLength", .unsigned8), .init(189, "ipHeaderLength", .unsigned8), .init(190, "totalLengthIPv4", .unsigned16),
        .init(191, "payloadLengthIPv6", .unsigned16), .init(192, "ipTTL", .unsigned8), .init(193, "nextHeaderIPv6", .unsigned8), .init(194, "mplsPayloadLength", .unsigned32),
        .init(195, "ipDiffServCodePoint", .unsigned8), .init(196, "ipPrecedence", .unsigned8), .init(197, "fragmentFlags", .unsigned8), .init(198, "octetDeltaSumOfSquares", .unsigned64),
        .init(199, "octetTotalSumOfSquares", .unsigned64), .init(200, "mplsTopLabelTTL", .unsigned8), .init(201, "mplsLabelStackLength", .unsigned32),
        .init(202, "mplsLabelStackDepth", .unsigned32), .init(203, "mplsTopLabelExp", .unsigned8), .init(204, "ipPayloadLength", .unsigned32),
        .init(205, "udpMessageLength", .unsigned16), .init(206, "isMulticast", .unsigned8), .init(207, "ipv4IHL", .unsigned8), .init(208, "ipv4Options", .unsigned32),
        .init(209, "tcpOptions", .unsigned64), .init(210, "paddingOctets", .octetArray), .init(211, "collectorIPv4Address", .ipv4Address),
        .init(212, "collectorIPv6Address", .ipv6Address), .init(213, "exportInterface", .unsigned32), .init(214, "exportProtocolVersion", .unsigned8),
        .init(215, "exportTransportProtocol", .unsigned8), .init(216, "collectorTransportPort", .unsigned16), .init(217, "exporterTransportPort", .unsigned16),
        .init(218, "tcpSynTotalCount", .unsigned64), .init(219, "tcpFinTotalCount", .unsigned64), .init(220, "tcpRstTotalCount", .unsigned64),
        .init(221, "tcpPshTotalCount", .unsigned64), .init(222, "tcpAckTotalCount", .unsigned64), .init(223, "tcpUrgTotalCount", .unsigned64),
        .init(224, "ipTotalLength", .unsigned64), .init(225, "postNATSourceIPv4Address", .ipv4Address), .init(226, "postNATDestinationIPv4Address", .ipv4Address),
        .init(227, "postNAPTSourceTransportPort", .unsigned16), .init(228, "postNAPTDestinationTransportPort", .unsigned16), .init(229, "natOriginatingAddressRealm", .unsigned8),
        .init(230, "natEvent", .unsigned8), .init(231, "initiatorOctets", .unsigned64), .init(232, "responderOctets", .unsigned64), .init(233, "firewallEvent", .unsigned8),
        .init(234, "ingressVRFID", .unsigned32), .init(235, "egressVRFID", .unsigned32), .init(236, "VRFname", .string), .init(237, "postMplsTopLabelExp", .unsigned8),
        .init(238, "tcpWindowScale", .unsigned16), .init(239, "biflowDirection", .unsigned8), .init(240, "ethernetHeaderLength", .unsigned8),
        .init(241, "ethernetPayloadLength", .unsigned16), .init(242, "ethernetTotalLength", .unsigned16), .init(243, "dot1qVlanId", .unsigned16),
        .init(244, "dot1qPriority", .unsigned8), .init(245, "dot1qCustomerVlanId", .unsigned16), .init(246, "dot1qCustomerPriority", .unsigned8),
        .init(247, "metroEvcId", .string), .init(248, "metroEvcType", .unsigned8), .init(249, "pseudoWireId", .unsigned32), .init(250, "pseudoWireType", .unsigned16),
        .init(251, "pseudoWireControlWord", .unsigned32), .init(252, "ingressPhysicalInterface", .unsigned32), .init(253, "egressPhysicalInterface", .unsigned32),
        .init(254, "postDot1qVlanId", .unsigned16), .init(255, "postDot1qCustomerVlanId", .unsigned16), .init(256, "ethernetType", .unsigned16),
        .init(257, "postIpPrecedence", .unsigned8), .init(258, "collectionTimeMilliseconds", .dateTimeMilliseconds), .init(259, "exportSctpStreamId", .unsigned16),
        .init(260, "maxExportSeconds", .dateTimeSeconds), .init(261, "maxFlowEndSeconds", .dateTimeSeconds), .init(262, "messageMD5Checksum", .octetArray),
        .init(263, "messageScope", .unsigned8), .init(264, "minExportSeconds", .dateTimeSeconds), .init(265, "minFlowStartSeconds", .dateTimeSeconds),
        .init(266, "opaqueOctets", .octetArray), .init(267, "sessionScope", .unsigned8), .init(268, "maxFlowEndMicroseconds", .dateTimeMicroseconds),
        .init(269, "maxFlowEndMilliseconds", .dateTimeMilliseconds), .init(270, "maxFlowEndNanoseconds", .dateTimeNanoseconds),
        .init(271, "minFlowStartMicroseconds", .dateTimeMicroseconds), .init(272, "minFlowStartMilliseconds", .dateTimeMilliseconds),
        .init(273, "minFlowStartNanoseconds", .dateTimeNanoseconds), .init(274, "collectorCertificate", .octetArray), .init(275, "exporterCertificate", .octetArray),
        .init(276, "dataRecordsReliability", .boolean), .init(277, "observationPointType", .unsigned8), .init(278, "newConnectionDeltaCount", .unsigned32),
        .init(279, "connectionSumDurationSeconds", .unsigned64), .init(280, "connectionTransactionId", .unsigned64), .init(281, "postNATSourceIPv6Address", .ipv6Address),
        .init(282, "postNATDestinationIPv6Address", .ipv6Address), .init(283, "natPoolId", .unsigned32), .init(284, "natPoolName", .string),
        .init(285, "anonymizationFlags", .unsigned16), .init(286, "anonymizationTechnique", .unsigned16), .init(287, "informationElementIndex", .unsigned16),
        .init(288, "p2pTechnology", .string), .init(289, "tunnelTechnology", .string), .init(290, "encryptedTechnology", .string), .init(291, "basicList", .basicList),
        .init(292, "subTemplateList", .subTemplateList), .init(293, "subTemplateMultiList", .subTemplateMultiList), .init(294, "bgpValidityState", .unsigned8),
        .init(295, "IPSecSPI", .unsigned32), .init(296, "greKey", .unsigned32), .init(297, "natType", .unsigned8), .init(298, "initiatorPackets", .unsigned64),
        .init(299, "responderPackets", .unsigned64), .init(300, "observationDomainName", .string), .init(301, "selectionSequenceId", .unsigned64),
        .init(302, "selectorId", .unsigned64), .init(303, "informationElementId", .unsigned16), .init(304, "selectorAlgorithm", .unsigned16),
        .init(305, "samplingPacketInterval", .unsigned32), .init(306, "samplingPacketSpace", .unsigned32), .init(307, "samplingTimeInterval", .unsigned32),
        .init(308, "samplingTimeSpace", .unsigned32), .init(309, "samplingSize", .unsigned32), .init(310, "samplingPopulation", .unsigned32),
        .init(311, "samplingProbability", .float64), .init(312, "dataLinkFrameSize", .unsigned16), .init(313, "ipHeaderPacketSection", .octetArray),
        .init(314, "ipPayloadPacketSection", .octetArray), .init(315, "dataLinkFrameSection", .octetArray), .init(316, "mplsLabelStackSection", .octetArray),
        .init(317, "mplsPayloadPacketSection", .octetArray), .init(318, "selectorIdTotalPktsObserved", .unsigned64), .init(319, "selectorIdTotalPktsSelected", .unsigned64),
        .init(320, "absoluteError", .float64), .init(321, "relativeError", .float64), .init(322, "observationTimeSeconds", .dateTimeSeconds),
        .init(323, "observationTimeMilliseconds", .dateTimeMilliseconds), .init(324, "observationTimeMicroseconds", .dateTimeMicroseconds),
        .init(325, "observationTimeNanoseconds", .dateTimeNanoseconds), .init(326, "digestHashValue", .unsigned64), .init(327, "hashIPPayloadOffset", .unsigned64),
        .init(328, "hashIPPayloadSize", .unsigned64), .init(329, "hashOutputRangeMin", .unsigned64), .init(330, "hashOutputRangeMax", .unsigned64),
        .init(331, "hashSelectedRangeMin", .unsigned64), .init(332, "hashSelectedRangeMax", .unsigned64), .init(333, "hashDigestOutput", .boolean),
        .init(334, "hashInitialiserValue", .unsigned64), .init(335, "selectorName", .string), .init(336, "upperCILimit", .float64), .init(337, "lowerCILimit", .float64),
        .init(338, "confidenceLevel", .float64), .init(339, "informationElementDataType", .unsigned8), .init(340, "informationElementDescription", .string),
        .init(341, "informationElementName", .string), .init(342, "informationElementRangeBegin", .unsigned64), .init(343, "informationElementRangeEnd", .unsigned64),
        .init(344, "informationElementSemantics", .unsigned8), .init(345, "informationElementUnits", .unsigned16), .init(346, "privateEnterpriseNumber", .unsigned32),
        .init(347, "virtualStationInterfaceId", .octetArray), .init(348, "virtualStationInterfaceName", .string), .init(349, "virtualStationUUID", .octetArray),
        .init(350, "virtualStationName", .string), .init(351, "layer2SegmentId", .unsigned64), .init(352, "layer2OctetDeltaCount", .unsigned64),
        .init(353, "layer2OctetTotalCount", .unsigned64), .init(354, "ingressUnicastPacketTotalCount", .unsigned64), .init(355, "ingressMulticastPacketTotalCount", .unsigned64),
        .init(356, "ingressBroadcastPacketTotalCount", .unsigned64), .init(357, "egressUnicastPacketTotalCount", .unsigned64), .init(358, "egressBroadcastPacketTotalCount", .unsigned64),
        .init(359, "monitoringIntervalStartMilliSeconds", .dateTimeMilliseconds), .init(360, "monitoringIntervalEndMilliSeconds", .dateTimeMilliseconds),
        .init(361, "portRangeStart", .unsigned16), .init(362, "portRangeEnd", .unsigned16), .init(363, "portRangeStepSize", .unsigned16), .init(364, "portRangeNumPorts", .unsigned16),
        .init(365, "staMacAddress", .macAddress), .init(366, "staIPv4Address", .ipv4Address), .init(367, "wtpMacAddress", .macAddress), .init(368, "ingressInterfaceType", .unsigned32),
        .init(369, "egressInterfaceType", .unsigned32), .init(370, "rtpSequenceNumber", .unsigned16), .init(371, "userName", .string), .init(372, "applicationCategoryName", .string),
        .init(373, "applicationSubCategoryName", .string), .init(374, "applicationGroupName", .string), .init(375, "originalFlowsPresent", .unsigned64),
        .init(376, "originalFlowsInitiated", .unsigned64), .init(377, "originalFlowsCompleted", .unsigned64), .init(378, "distinctCountOfSourceIPAddress", .unsigned64),
        .init(379, "distinctCountOfDestinationIPAddress", .unsigned64), .init(380, "distinctCountOfSourceIPv4Address", .unsigned32),
        .init(381, "distinctCountOfDestinationIPv4Address", .unsigned32), .init(382, "distinctCountOfSourceIPv6Address", .unsigned64),
        .init(383, "distinctCountOfDestinationIPv6Address", .unsigned64), .init(384, "valueDistributionMethod", .unsigned8), .init(385, "rfc3550JitterMilliseconds", .unsigned32),
        .init(386, "rfc3550JitterMicroseconds", .unsigned32), .init(387, "rfc3550JitterNanoseconds", .unsigned32), .init(388, "dot1qDEI", .boolean),
        .init(389, "dot1qCustomerDEI", .boolean), .init(390, "flowSelectorAlgorithm", .unsigned16), .init(391, "flowSelectedOctetDeltaCount", .unsigned64),
        .init(392, "flowSelectedPacketDeltaCount", .unsigned64), .init(393, "flowSelectedFlowDeltaCount", .unsigned64), .init(394, "selectorIDTotalFlowsObserved", .unsigned64),
        .init(395, "selectorIDTotalFlowsSelected", .unsigned64), .init(396, "samplingFlowInterval", .unsigned64), .init(397, "samplingFlowSpacing", .unsigned64),
        .init(398, "flowSamplingTimeInterval", .unsigned64), .init(399, "flowSamplingTimeSpacing", .unsigned64), .init(400, "hashFlowDomain", .unsigned16),
        .init(401, "transportOctetDeltaCount", .unsigned64), .init(402, "transportPacketDeltaCount", .unsigned64), .init(403, "originalExporterIPv4Address", .ipv4Address),
        .init(404, "originalExporterIPv6Address", .ipv6Address), .init(405, "originalObservationDomainId", .unsigned32), .init(406, "intermediateProcessId", .unsigned32),
        .init(407, "ignoredDataRecordTotalCount", .unsigned64), .init(408, "dataLinkFrameType", .unsigned16), .init(409, "sectionOffset", .unsigned16),
        .init(410, "sectionExportedOctets", .unsigned16), .init(411, "dot1qServiceInstanceTag", .octetArray), .init(412, "dot1qServiceInstanceId", .unsigned32),
        .init(413, "dot1qServiceInstancePriority", .unsigned8), .init(414, "dot1qCustomerSourceMacAddress", .macAddress), .init(415, "dot1qCustomerDestinationMacAddress", .macAddress),
        .init(417, "postLayer2OctetDeltaCount", .unsigned64), .init(418, "postMCastLayer2OctetDeltaCount", .unsigned64), .init(420, "postLayer2OctetTotalCount", .unsigned64),
        .init(421, "postMCastLayer2OctetTotalCount", .unsigned64), .init(422, "minimumLayer2TotalLength", .unsigned64), .init(423, "maximumLayer2TotalLength", .unsigned64),
        .init(424, "droppedLayer2OctetDeltaCount", .unsigned64), .init(425, "droppedLayer2OctetTotalCount", .unsigned64), .init(426, "ignoredLayer2OctetTotalCount", .unsigned64),
        .init(427, "notSentLayer2OctetTotalCount", .unsigned64), .init(428, "layer2OctetDeltaSumOfSquares", .unsigned64), .init(429, "layer2OctetTotalSumOfSquares", .unsigned64),
        .init(430, "layer2FrameDeltaCount", .unsigned64), .init(431, "layer2FrameTotalCount", .unsigned64), .init(432, "pseudoWireDestinationIPv4Address", .ipv4Address),
        .init(433, "ignoredLayer2FrameTotalCount", .unsigned64), .init(434, "mibObjectValueInteger", .signed32), .init(435, "mibObjectValueOctetString", .octetArray),
        .init(436, "mibObjectValueOID", .octetArray), .init(437, "mibObjectValueBits", .octetArray), .init(438, "mibObjectValueIPAddress", .ipv4Address),
        .init(439, "mibObjectValueCounter", .unsigned64), .init(440, "mibObjectValueGauge", .unsigned32), .init(441, "mibObjectValueTimeTicks", .unsigned32),
        .init(442, "mibObjectValueUnsigned", .unsigned32), .init(443, "mibObjectValueTable", .subTemplateList), .init(444, "mibObjectValueRow", .subTemplateList),
        .init(445, "mibObjectIdentifier", .octetArray), .init(446, "mibSubIdentifier", .unsigned32), .init(447, "mibIndexIndicator", .unsigned64),
        .init(448, "mibCaptureTimeSemantics", .unsigned8), .init(449, "mibContextEngineID", .octetArray), .init(450, "mibContextName", .string),
        .init(451, "mibObjectName", .string), .init(452, "mibObjectDescription", .string), .init(453, "mibObjectSyntax", .string), .init(454, "mibModuleName", .string),
        .init(455, "mobileIMSI", .string), .init(456, "mobileMSISDN", .string), .init(457, "httpStatusCode", .unsigned16), .init(458, "sourceTransportPortsLimit", .unsigned16),
        .init(459, "httpRequestMethod", .string), .init(460, "httpRequestHost", .string), .init(461, "httpRequestTarget", .string), .init(462, "httpMessageVersion", .string),
        .init(463, "natInstanceID", .unsigned32), .init(464, "internalAddressRealm", .octetArray), .init(465, "externalAddressRealm", .octetArray),
        .init(466, "natQuotaExceededEvent", .unsigned32), .init(467, "natThresholdEvent", .unsigned32), .init(468, "httpUserAgent", .string),
        .init(469, "httpContentType", .string), .init(470, "httpReasonPhrase", .string), .init(471, "maxSessionEntries", .unsigned32),
        .init(472, "maxBIBEntries", .unsigned32), .init(473, "maxEntriesPerUser", .unsigned32), .init(474, "maxSubscribers", .unsigned32),
        .init(475, "maxFragmentsPendingReassembly", .unsigned32), .init(476, "addressPoolHighThreshold", .unsigned32), .init(477, "addressPoolLowThreshold", .unsigned32),
        .init(478, "addressPortMappingHighThreshold", .unsigned32), .init(479, "addressPortMappingLowThreshold", .unsigned32),
        .init(480, "addressPortMappingPerUserHighThreshold", .unsigned32), .init(481, "globalAddressMappingHighThreshold", .unsigned32),
        .init(482, "vpnIdentifier", .octetArray), .init(483, "bgpCommunity", .unsigned32), .init(484, "bgpSourceCommunityList", .basicList),
        .init(485, "bgpDestinationCommunityList", .basicList), .init(486, "bgpExtendedCommunity", .octetArray), .init(487, "bgpSourceExtendedCommunityList", .basicList),
        .init(488, "bgpDestinationExtendedCommunityList", .basicList), .init(489, "bgpLargeCommunity", .octetArray), .init(490, "bgpSourceLargeCommunityList", .basicList),
        .init(491, "bgpDestinationLargeCommunityList", .basicList),
    ]
}
