import Foundation
import NetSentryCore
import NetSentryCorrelation
import NetSentryDetection

/// Human-readable incident report for one alert plus its investigation timeline, and a machine-readable bundle.
public enum IncidentExport {
    public static func markdown(alert a: Alert, clientLabel: String?, investigation: Investigation?, policy: RedactionPolicy, isInternal: (IPAddress) -> Bool) -> String {
        let r = Redactor(policy)
        func t(_ s: String) -> String { r.text(s, isInternal: isInternal) }
        var md = "# Incident report: \(t(a.title))\n\n"
        md += "Generated by \(Branding.productName) on \(ISO.string(.now)). Redaction: \(policy.summary).\n\n"
        md += "| | |\n|---|---|\n"
        md += "| Rule | `\(a.ruleName)` v\(a.ruleVersion) |\n| Severity | \(a.severity.label) |\n| State | \(a.state.rawValue) |\n"
        md += "| First occurrence | \(ISO.string(a.firstOccurrence)) |\n| Last occurrence | \(ISO.string(a.lastOccurrence)) (\(a.occurrenceCount)×) |\n"
        md += "| Entity | \(a.entity.kind): \(t(a.entity.label)) |\n"
        if let c = a.clientID { md += "| Client | #\(c)\(clientLabel.map { " " + r.hostname($0) } ?? "") |\n" }
        md += "\n## Summary\n\n\(t(a.summary))\n\n## Why it triggered\n\n\(t(a.explanation))\n\n"
        if let b = a.baseline { md += "## Baseline\n\n\(b.kind): \(String(format: "%g", b.value)) \(b.unit) over \(b.period) (\(b.samples) samples)\n\n" }
        md += "## Evidence\n\n"
        for (k, v) in a.evidence.sorted(by: { $0.key < $1.key }) { md += "- **\(k)**: \(t(v))\n" }
        md += "\nReferenced records: \(a.flowIDs.count) flows, \(a.eventIDs.count) events.\n\n"
        if !a.steps.isEmpty { md += "## Recommended investigation\n\n"; for s in a.steps { md += "1. \(t(s))\n" }; md += "\n" }
        if !a.notes.isEmpty { md += "## Analyst notes\n\n"; for n in a.notes { md += "- \(ISO.string(n.createdAt)): \(policy.dropNotes ? "[note removed]" : t(n.text))\n" }; md += "\n" }
        if let inv = investigation {
            md += "## Timeline (\(inv.entries.count) entries, \(inv.truncated ? "truncated" : "complete"))\n\n"
            md += "Relations describe shared attributes and timing only; they do not assert causation.\n\n| Time | Kind | Entry | Relation |\n|---|---|---|---|\n"
            for e in inv.entries {
                md += "| \(ISO.string(e.time)) | \(e.kind.rawValue)\(e.isAnchor ? " (anchor)" : "") | \(t(e.title).replacingOccurrences(of: "|", with: "\\|")) | \(e.relations.joined(separator: "; ")) |\n"
            }
            md += "\n"
        }
        md += "---\nThis report was produced by deterministic rules; every statement above is traceable to the listed evidence.\n"
        return md
    }

    public struct Bundle: Codable, Sendable {
        public var format = "netsentry-investigation/1"
        public var product = Branding.productName
        public var generatedAt = ISO.string(.now)
        public var redaction: String
        public var anchor: String
        public var rangeStart: String
        public var rangeEnd: String
        public var truncated: Bool
        public var alert: ExportedAlert?
        public var entries: [Entry]
        public struct Entry: Codable, Sendable {
            public var time: String, kind: String, title: String, detail: String, relations: [String], isAnchor: Bool
            public var flow: ExportedFlow?, event: ExportedEvent?, alertID: Int64?
        }
    }

    public struct ExportedAlert: Codable, Sendable {
        public var id: Int64, rule: String, ruleVersion: Int, severity: String, state: String, title: String, summary: String, explanation: String
        public var firstOccurrence: String, lastOccurrence: String, occurrences: Int, entityKind: String, entity: String, clientID: Int64?
        public var evidence: [String: String], flowIDs: [Int64], eventIDs: [Int64], steps: [String], notes: [String]
        public init(_ a: Alert, redactor r: Redactor, isInternal: (IPAddress) -> Bool) {
            func t(_ s: String) -> String { r.text(s, isInternal: isInternal) }
            id = a.id; rule = a.ruleName; ruleVersion = a.ruleVersion; severity = a.severity.label; state = a.state.rawValue
            title = t(a.title); summary = t(a.summary); explanation = t(a.explanation)
            firstOccurrence = ISO.string(a.firstOccurrence); lastOccurrence = ISO.string(a.lastOccurrence); occurrences = a.occurrenceCount
            entityKind = a.entity.kind; entity = t(a.entity.label); clientID = a.clientID
            evidence = a.evidence.mapValues(t); flowIDs = a.flowIDs; eventIDs = a.eventIDs; steps = a.steps.map(t)
            notes = a.notes.map { r.policy.dropNotes ? "[note removed]" : "\(ISO.string($0.createdAt)): \(t($0.text))" }
        }
    }

    public static func alertsJSON(_ alerts: [Alert], policy: RedactionPolicy, isInternal: (IPAddress) -> Bool) throws -> Data {
        let r = Redactor(policy)
        return try RecordExport.encoder.encode(RecordExport.Envelope(kind: "alerts", redaction: policy.summary, count: alerts.count, records: alerts.map { ExportedAlert($0, redactor: r, isInternal: isInternal) }))
    }

    public static func alertsCSV(_ alerts: [Alert], policy: RedactionPolicy, isInternal: (IPAddress) -> Bool) -> String {
        let r = Redactor(policy)
        var out = CSV.line(["id", "rule", "severity", "state", "first_occurrence", "last_occurrence", "occurrences", "entity_kind", "entity", "client_id", "title", "summary"])
        for a in alerts {
            let x = ExportedAlert(a, redactor: r, isInternal: isInternal)
            out += CSV.line(["\(x.id)", x.rule, x.severity, x.state, x.firstOccurrence, x.lastOccurrence, "\(x.occurrences)", x.entityKind, x.entity, x.clientID.map { "\($0)" } ?? "", x.title, x.summary])
        }
        return out
    }

    public static func bundle(_ inv: Investigation, alert: Alert?, policy: RedactionPolicy, isInternal: (IPAddress) -> Bool) throws -> Data {
        let r = Redactor(policy)
        let entries = inv.entries.map { e in
            Bundle.Entry(time: ISO.string(e.time), kind: e.kind.rawValue, title: r.text(e.title, isInternal: isInternal), detail: r.text(e.detail, isInternal: isInternal), relations: e.relations, isAnchor: e.isAnchor,
                         flow: e.flow.map { ExportedFlow($0, redactor: r) }, event: e.event.map { ExportedEvent($0, redactor: r, isInternal: isInternal) }, alertID: e.alertID)
        }
        let b = Bundle(redaction: policy.summary, anchor: r.text(inv.request.anchor.label, isInternal: isInternal), rangeStart: ISO.string(inv.request.range.start), rangeEnd: ISO.string(inv.request.range.end),
                       truncated: inv.truncated, alert: alert.map { ExportedAlert($0, redactor: r, isInternal: isInternal) }, entries: entries)
        return try RecordExport.encoder.encode(b)
    }
}
